### ISSUE TITLE
GrpcTransportOptions uses internal grpc APIs

### ISSUE THREAD

**Issue by ejona86** [googleapis/java-core#1009]
This is reopening https://github.com/googleapis/java-core/issues/120 which should not have been closed. Internal APIs change without warning, which would break your users. Please remove the usage of the internal APIs.

https://github.com/googleapis/java-core/blob/13414b607c7b2cd51a865cde9b3e479d82e96dfa/google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java#L35-L36

**Comment by suztomo** [comment]
Memo: that's the only places in this repository that touch `io.grpc.internal` package:

```
~/java-core $ grep -ir 'import io.grpc.internal' .                                                       git[branch:main]
./google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java:import io.grpc.internal.SharedResourceHolder;
./google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java:import io.grpc.internal.SharedResourceHolder.Resource;
```

**Comment by ejona86** [comment]
What sort of timeframe does p3 mean this might get fixed? I opened the original issue 3.5 years ago. P3 makes me worry it will be another 3 years and nothing will have happened here. Given this is a diamond dependency danger, it seems inappropriate to be p3.

If this is fixed tomorrow, it will still be an issue for another year-ish afterward, as users should be able to upgrade their grpc version at-will and they may be using an older java-core version.

**Comment by suztomo** [comment]
@ejona86 I'm afraid p3 is not high priority and it may not match the urgency you have in mind. Do you have a plan to remove or restrict the access of the`io.grpc.internal.SharedResourceHolder`? It may change the priority in our team.

**Comment by suztomo** [comment]
@chingor13 I see https://github.com/googleapis/java-core/pull/129 might fix the issue. What was the problem that prevented you from merging it?
