### ISSUE TITLE
Use java-shared-dependencies/third-party-dependencies where possible

### ISSUE THREAD

**Issue by burkedavison** [googleapis/java-core#1091]
We should add an import-scoped [java-shared-dependencies/third-party-dependencies](https://github.com/googleapis/java-shared-dependencies/blob/main/third-party-dependencies/pom.xml) entry in [the `dependency-management` section](https://github.com/googleapis/java-core/blob/main/pom.xml#L176-L190) of java-core's `pom.xml`, remove the associated version declarations in java-core, and consider offloading any remaining third-party dependency versions to third-party-dependencies.

**Comment by suztomo** [comment]
In google-cloud-java, java-core uses the shared dependencies BOM, which imports third-party-dependencies.
