### ISSUE TITLE
GrpcTransportOptions uses internal grpc APIs

### ISSUE THREAD

**Issue by ejona86** [googleapis/java-core#120]
`GrpcTransportOptions` references `io.grpc.internal.SharedResourceHolder`. As it is in the internal package, it has an unstable API that may change at any time.

https://github.com/googleapis/google-cloud-java/blob/6b567115e98271632bdaa04833fdd9e217bd9c3e/google-cloud-clients/google-cloud-core-grpc/src/main/java/com/google/cloud/grpc/GrpcTransportOptions.java#L35-L36

**Comment by meltsufin** [comment]
It's only used in an internal api of `java-core`. So, it should be safe in case it has to change. Please re-open, if needed.

**Comment by ejona86** [comment]
Please re-open.

No, this isn't about whether the API is exposed to your users. Libraries _must not_ use unstable APIs in other libraries as libraries cannot dictate which version of libraries are being used.

**Comment by meltsufin** [comment]
@chingor13 You had a PR open to fix it, but you closed it. Why?
