### ISSUE TITLE
Core: ServiceOptions.setCredentials fails with ClassCastException when using UserCredentials

### ISSUE THREAD

**Issue by vladimir-lu** [googleapis/java-core#123]
On line https://github.com/googleapis/java-core/blob/6aa4476441fd7636dd116516d3bf4b738cf8a8a9/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L221 the check is `instanceof QuotaProjectIdProvider` but the cast is to `ServiceAccountCredentials` therefore you get 

```
class com.google.auth.oauth2.UserCredentials cannot be cast to class com.google.auth.oauth2.ServiceAccountCredentials (com.google.auth.oauth2.UserCredentials and com.google.auth.oauth2.ServiceAccountCredentials are in unnamed module of loader 'app')
```

The cast needs to be changed. `google-cloud-core` version 1.92.0

**Comment by chingor13** [comment]
Thanks for finding this and reporting it! It's definitely a bug and we'll fix and push a release.
