### ISSUE TITLE
Include LICENSE in jar files

### ISSUE THREAD

**Issue by jeff303** [googleapis/java-core#488]
**Is your feature request related to a problem? Please describe.**
The jar artifacts produced out of this repository do not include the `LICENSE` file.

**Describe the solution you'd like**
Include `LICENSE` in any built jar artifacts.

**Describe alternatives you've considered**
Manual overrides for our license detection/handling code, for Google Cloud libraries.

**Comment by suztomo** [comment]
The license information is in pom.xml. Maven reads it.

https://search.maven.org/artifact/com.google.cloud/google-cloud-core/2.10.0/jar
