### ISSUE TITLE
FR: support for HTTP proxy & SOCKS proxy

### ISSUE THREAD

**Issue by lesv** [googleapis/java-core#88]
Many corporate networks require the use of either a [HTTP Proxy](https://en.wikipedia.org/wiki/Proxy_server) or a [SOCKS](https://en.wikipedia.org/wiki/SOCKS) proxy.  Our client libraries should support this.

@bullet-tooth in google/google-auth-library-java#127 asked that we support both an `HTTP_PROXY` and `SOCKS_PROXY` in our auth libraries.  We need to also support through all the client libraries as many of our customers have this issue on their corporate networks.

@jonparrott FYI
@garrettjonesgoogle FYI

**Comment by lesv** [comment]
Some reason this popped up on my notifier today.   A quick search found two things you should consider:

* https://stackoverflow.com/questions/46288195/grpc-from-client-to-server-with-forward-proxy  see user2310395 answer.
* https://groups.google.com/g/grpc-io/c/IeFUjHiP4UE  <== Release notes for 1.8.0 grpc (See behavior changes)

**Comment by suztomo** [comment]
@lesv  Is this issue still valid? You seem to have found solutions. If not, please reopen this.
